# File name: buttondock.kv
<ButtonDock@BoxLayout>:
    BoxLayout:
        orientation: 'vertical'
        padding: 4
        font_size: 32
        Button:
            color: 0, 1, 0, 1
            text: 'WiFi'
        Button:
            color: 0, 1, 0, 1
            text: 'Reboot'
        Button:
            color: 0, 1, 0, 1
            text: 'LockDown'
        Button:
            color: 0, 1, 0, 1
            text: 'Exit'
